spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_srm_platform?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
  application:
    name: ms_srm_platform
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false

server:
  port: 8080
  max-http-header-size: 4048576
